[paths]
app_path = "app/src/main/assets/python/app"
app_packages_path = "app/src/main/assets/python/app_packages"
support_path = "."

icon.48 = "app/src/main/res/mimap-mpdi/ic_launcher_round.png"
icon.72 = "app/src/main/res/mimap-hpdi/ic_launcher_round.png"
icon.96 = "app/src/main/res/mimap-xhpdi/ic_launcher_round.png"
icon.144 = "app/src/main/res/mimap-xxhpdi/ic_launcher_round.png"
icon.192 = "app/src/main/res/mimap-xxxhpdi/ic_launcher_round.png"

# icon.48 = "app/src/main/res/mimap-mpdi/ic_launcher.png"
# icon.72 = "app/src/main/res/mimap-hpdi/ic_launcher.png"
# icon.96 = "app/src/main/res/mimap-xhpdi/ic_launcher.png"
# icon.144 = "app/src/main/res/mimap-xxhpdi/ic_launcher.png"
# icon.192 = "app/src/main/res/mimap-xxxhpdi/ic_launcher.png"

# splash.750x1334 = "app/src/main/res/.../launch-750x1334.png"
